# Neural Network Foundations with TF2.0

#### First Example of Tf2.0

In [54]:
W=tf.Variable(tf.ones([2,2]))
b=tf.Variable(tf.zeros([2]))

In [57]:
W.shape

TensorShape([2, 2])

In [71]:
x=tf.ones((2))

In [72]:
print(x)

tf.Tensor([1. 1.], shape=(2,), dtype=float32)


In [37]:
W.dtype

tf.float32

In [38]:
b.dtype

tf.float32

In [46]:
@tf.function
def model(x):
    return x*W+b

In [47]:
out_a=model([1,0])

2022-07-22 18:21:40.585331: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [48]:
out_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [1., 0.]], dtype=float32)>

In [49]:
# Sequential model

In [75]:
model=tf.keras.models.Sequential()

In [76]:
model.add(tf.keras.layers.Dense(10,input_shape=(20,),kernel_initializer='random_uniform',name='dense-layer',activation='softmax'))

In [78]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense-layer (Dense)         (None, 10)                210       
                                                                 
Total params: 210
Trainable params: 210
Non-trainable params: 0
_________________________________________________________________
